name: azlistview
description: A Flutter sticky headers & index ListView. IndexBar. such as citylist, contactlist. index and hover effect.
version: 2.0.0
homepage: https://github.com/flutterchina/azlistview

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0